### ISSUE TITLE
Apply damage to bubble colums

### ISSUE THREAD

**Issue by Boy0000** [MineInAbyss/BoneHurtingJuice#11]
Using bubble colums should damage the player like waterfall does, both upwards and downwards.

**Comment by Boy0000** [comment]
Fixed in Liz's repo.. seems i still had that forked from back in the day.

**Comment by c-sig** [comment]
isnt curse enough for the ascending part? descending with a bubble column is also way slower than just dropping down.
maybe make player lose air bubbles instead rather than killing them since this also becomes a real easy way to trick players to dying

**Comment by Boy0000** [comment]
It would damage you identically to a waterfall so if you haven't realized by the time you find one that water = bad then well.
Yes it is slow down, but so are ladders. Same thing, its not the speed it is the fact you can just AFK on them with minimal to no risk.

The curse means very little when you have some protection armor, even when ascending it rapidly. So if a player is prepared enough with good gear the curse would not be an issue. There is a reason it is used right now on the server.

The bubble idea is already a vanilla feature, and adding enchants makes the time you can be in one fairly decent, enough to ascend very far. If you wanna shorten the air-time you could add it in. There are also checks for what way the bubblecolumn is going if one would only want damage one way.
